/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'shany' at '12/10/16 1:03 AM' with Gradle 3.2.1
 *
 * @author shany, @date 12/10/16 1:03 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
