language: scala
scala:
  - 2.11.8
  - 2.10.6
jdk:
  - oraclejdk8
services:
  - rabbitmq
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
